### ISSUE TITLE
TODO: Find a way to access variables (being somewhere else in the stack)

### ISSUE THREAD

**Issue by Lurulai** [LOLCODERZ/NOPE#3]
Pick a method:

- [ ] Pop everything until we access the correct variable [Slow 😢]

- [ ] Store variables in 2nd stack [Still slow]

- [x] Store variables on the stack with a Map linking the variables with their address (pointer):
In case of early free (keep it in mind [memory]) and free it once on top of the stack (normal free)
To avoid having empty space in the memory
Pretty fast (cannot really be considered a stack any more, though) [definitely avoid Linked List in this case]
